version: "3"

services:
  beer-quest-api:
    build: api/.
    ports:
      - "8081:80"
  beer-quest-web:
    build:
      context: web/.
      args:
        - "REACT_APP_API_HOST=http://localhost:8081"
    ports:
      - "8080:80"
